### ISSUE TITLE
A User Can Fill Out a Product Entry

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#104]

**Comment by candyj0311** [comment]
![image](https://cloud.githubusercontent.com/assets/10750162/13408308/1df8c17a-defb-11e5-938e-ef6f481ad1b2.png)

**Comment by candyj0311** [comment]
This depends on 111.

**Comment by candyj0311** [comment]
See product inventory options here: https://github.com/MobilityLabs/pdredesign-server/wiki/Data-and-Product-Inventories

**Comment by MakotoTheKnight** [comment]
Backend Approach
---

 - Create, Read (individual entity, list) and Update route as a child of `/inventories` (so something like `/inventories/:id/product_entries`
 - Must have a parent inventory before creation is possible
 - Create all values through the `ProductEntry` table.

Each category - general questions, product questions, usage questions, and technical questions - has their own associated models, but for this, we should create them through the `ProductEntry`.  The model should already accept nested attributes for all of the above.

A resource to access all of the options provided from the model's enums should be exposed for ease of retrieving questions and options.  Most of the fields do not allow free-form entry and have validations against that; options that have a custom enum key  (e.g. `TechnicalQuestion.platforms[:custom]`) are not validated since they may contain any text available.

Some caution should be advised on `GeneralInventoryQuestion#price`, since it stores the data as a `DECIMAL(9, 2)`.  If we're concerned that may cause inaccuracies in storage, then we should adjust that in a migration with this task.

Frontend Approach
---

 - Form should live in its own directive
 - Should be one giant form with multiple values on it
 - Error messages should ideally show up on the fields that are invalid (i.e. if the name is missing or invalid, that input box should indicate an error); touch base with UX to be sure that this is the case and which colors we need to use

We do not yet have a permanent home for the button that will invoke this, but the idea is that this should be readily accessible from the `$modal` service, analogous to how `LearningQuestion` can be invoked.  Thus, a directive is an ideal approach to this:

```
$scope.modal = $modal.open({
  template: '<learning-question-modal reminder="true" />',
  scope: $scope
});
```

For the time being and to facilitate rapid development, it's okay if the listing of created product entries is on a separate page.  On the completion of #144, it is expected that those values will migrate to a spot on that page.

**Comment by candyj0311** [comment]
Changing Pricing Structure response so that users can choose Other as an option. We can add ability to input text in that field later as an enhancement.

**Comment by juliosantos** [comment]
"Connectivity" moved out into #165

**Comment by juliosantos** [comment]
slider for "estimated usage" moved out into #168
