### ISSUE TITLE
Product Entries: Connectivity Section

### ISSUE THREAD

**Issue by juliosantos** [MobilityLabs/pdredesign-server#165]
This was moved out of #104 for simplicity, and also because the search is probably generifiable.

**Comment by MakotoTheKnight** [comment]
We will need to transform the `technical_questions` table to fit our needs.

This will take the form of several intermediate goals:

 - Rework the `technical_questions` table to accept an `integer[]` instead of `text`.
 - Create an endpoint to bring back all product entries associated to current inventory's district, ideally with only the product ID and the product name as a JSON payload.
 - Add this into the form.

**Comment by juliosantos** [comment]
@candyj0311 the connectivity list shows a list of what I assume is `product_name`s, from the product entries' `general_inventory_question` section. What do we show when the name hasn't been filled yet?

**Comment by candyj0311** [comment]
Great question - Cat recommends making the name field required based on what we heard in user testing, so it sounds like there's a need to prioritize that if it's not a heavy lift. If we go with an answer to another entry to connect, that could get confusing.

**Comment by juliosantos** [comment]
Shouldn't be a heavy lift. I'll continue as planned and capture this in an new issue

**Comment by juliosantos** [comment]
#209
