### ISSUE TITLE
About page for pdredesign

### ISSUE THREAD

**Issue by rickymetz** [MobilityLabs/pdredesign-server#170]

**Comment by candyj0311** [comment]
This should include information about all of tools, their value when combined, and how they fit together.

**Comment by HeyCat** [comment]
So @candyj0311 is still aggregating copy for these pages, but I know we wanted to get this live sooner rather than later:
1. High level naming convention that @candyj0311 made: [(https://docs.google.com/a/mobility-labs.com/document/d/1ZtrSoJ0ntD5Cgl19Ozuzz2ANO-WTCv-R-SBuhgZNndo/edit?usp=sharing
)]
2.. The skeleton of the about + sidebar linking to other about pages and functionality will be consistent across all pages. 
3. While on a tool's about page, do not link to said about page in the sidebar (obvious I know, but I figured I'd mention it).
4. The orange copy is TBD  (and should appear live as grey), I am hoping to teach @candyj0311 Git enough to make these edits autonomously. 

Let me know if you have questions about these!

**Comment by HeyCat** [comment]
![about_dt_analysis](https://cloud.githubusercontent.com/assets/5464910/14351730/e1975c20-fc9e-11e5-912f-afcb63ecb295.png)
![about_dt_inventory](https://cloud.githubusercontent.com/assets/5464910/14351728/e1956d98-fc9e-11e5-99cd-efd5241e1017.png)
![about_pdredesign](https://cloud.githubusercontent.com/assets/5464910/14351731/e1982326-fc9e-11e5-8edd-16f5ac822c41.png)
![about_ra_assessment](https://cloud.githubusercontent.com/assets/5464910/14351729/e1965ed8-fc9e-11e5-885d-722ee51d8913.png)

**Comment by HeyCat** [comment]
![about_dt_analysis](https://cloud.githubusercontent.com/assets/5464910/14572940/cc6dce7e-031f-11e6-891b-3ec2cff2ad43.png)
![about_dt_inventory](https://cloud.githubusercontent.com/assets/5464910/14572941/cc7202d2-031f-11e6-8201-5a437b973699.png)
![about_pdredesign](https://cloud.githubusercontent.com/assets/5464910/14572943/cc7cc168-031f-11e6-83ba-5c7604d2c1df.png)
![about_ra_assessment](https://cloud.githubusercontent.com/assets/5464910/14572942/cc73bb72-031f-11e6-86ed-a052446bd558.png)
