### ISSUE TITLE
District members do not currently have a district assigned to them after being invited

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#214]
Current tasks:

- [x] Explore flow with registration; observe behavior of registration after user has been invited and has not clicked the registration link
- [x] Verify that user cannot register without providing a district
- [x] Verify that a user cannot recreate their account if invited to more than one assessment
- [x] Clean up assessment that has users without the right district

**Comment by MakotoTheKnight** [comment]
After backend investigation, we discovered that there is the possibility for a user to register their account even if they did not click on the registration link.  This has the potential to supersede any district they were invited to, implying that if they did not select a district (as was the original flow), they wouldn't have any districts attached to their account.

There are ways to fix this:

 - Prevent registration and send helpful message if user has an invite
 - Silently take the user account's district information and copy it over to the new account

**Comment by MakotoTheKnight** [comment]
We have verified that a user can "recreate" their account if they are invited to more than one assessment, and they do not click on the link in the email.

**Comment by juliosantos** [comment]
We should coerce the user into the correct flow. If they're registering and there's an invitation for them, we should tell them "go click the link in the email".

Also, as it stands, the user can re-create his account multiple times. We should get rid of `find_by_invite_or_initialize`, use the normal `.create` instead of `.save` in `users#create`,  and if `.create` succeeds we find the invitation and destroy it.
