### ISSUE TITLE
Analysis Consensus - Controller

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#266]
We require a controller to handle the same functionality as the existing ConsensusController, which is geared toward assessments.

This also includes adding the questions to the database (found  at https://docs.google.com/spreadsheets/d/1ladm2pK-bSp9VVSA8mra8VsGPg1p6GxG2klrEY8ROFE/edit#gid=0).  Note that "Category" translates to "Question" in the backend, and the "Category Definition" should actually be the body of the question.

**Comment by jkshepperson** [comment]
Per Jason request, merging #234 with this ticket since the functionality overlaps. Information from ticket #234 found here for easy reference from Cat/Candy comments: 

Candy 4/15/16: Facilitators can add a product or data set to a schema (PD category) in the Analysis as evidence. 
They should click the "Add Product" link which makes a modal appear. They choose product(s) or data set(s) from the modal and it is added to the Data/Product entry field.
Depends on #235.

Candy 4/20/16: The Supporting Data and Supporting Products should have a fixed height. If a facilitator adds tons of products to a category, a scroll bar will appear.

Cat wireframe attached from 4/20/16
![dta](https://cloud.githubusercontent.com/assets/15215098/14929488/a596d522-0e2b-11e6-90fd-9bf66eeab741.png)
