### ISSUE TITLE
'Mark Inventory as Complete' not updating %completed number correctly

### ISSUE THREAD

**Issue by jkshepperson** [MobilityLabs/pdredesign-server#279]
When I'm editing an inventory and I click 'Mark Inventory as Complete', and select 'OK' from the verification prompt popup, two issues are happening:
*EB = Expected Behavior

1. I am not taken anywhere after I click 'OK' from the prompt
EB: user is navigated to the report page with updated metrics

2. When I manually access the dashboard page after I have clicked 'Mark Inventory as Complete', the numbers associated with my inventory do not match my actions. 
EB: the number of 'completed' inventories should match the number of participants who have clicked 'mark inventory as complete'.
EB: the %complete visual graphic should be calculated as (number of participants invited to the inventory that have 'completed' the inventory)/(total number of participants invited to the inventory)

![image](https://cloud.githubusercontent.com/assets/15215098/14895193/6871938a-0d45-11e6-807c-9cd6b0147862.png)

**Comment by MakotoTheKnight** [comment]
Points in turn:

1.  The navigation should take you to the inventory report page and this page has been developed with that route in anticipation.  #260 needs to be closed before that flow can be considered complete.

2.  This is a straightforward fix; we currently increment the number of total responses and that's reflected in the inventory model directly.  What we need to do here is:

  - Debounce the button (add a delay) for about a second so that multiple firings don't submit repeatedly
  - Add logic to ensure that one user counts as one submission in the `InventoryResponse` model.

**Comment by jkshepperson** [comment]
Task is no loner relevant based on changes detailed in #292, #298 and #299 - we are changing the functionality so that an inventory is never 'completed' and thus is always available to be updated with new product or data entries.
