### ISSUE TITLE
Sent Messages section within an inventory is displaying incorrect messages

### ISSUE THREAD

**Issue by jkshepperson** [MobilityLabs/pdredesign-server#284]
When viewing an inventory dashboard page, the Sent Message section is displaying messages that do not match to the inventories data. 

For example: navigate to .../inventories/6/dashboard

1. Currently, the sorting of the messages is unclear
EB: Messages should be sorted chronologically, from newest to oldest

2. Some messages reflect dates as old as 2014
EB: Messages displaying in the Sent Messages section should only show messages for that inventory

![image](https://cloud.githubusercontent.com/assets/15215098/14896560/59593504-0d4c-11e6-9297-10f8aef490b1.png)

**Comment by MakotoTheKnight** [comment]
I don't observe the same issue as was originally reported, but I'll do some investigation on the ordering of these messages.

**Comment by MakotoTheKnight** [comment]
Notes:

 - Messages are populated with a default message.  This default message does not appear in the database.  This causes an issue when attempting to select and/or order messages based on their creation date.
 - The issue of messages bleeding through based on the ID alone has been indeed resolved.  Messages are polymorphic which means that they require both an ID and a type to ensure that we only pull back the type we care about.  Since I can observe that this happens, there should not be any issues with any messages bleeding through.
 - The main fix to this will be in two parts:  first is to migrate all existing default messages over to the Messages table, and the second is to place a default order on the messages coming back from the database.

**Comment by HeyCat** [comment]
<img width="1048" alt="screen shot 2016-09-02 at 11 26 58" src="https://cloud.githubusercontent.com/assets/5464910/18209086/36c5187e-7100-11e6-882d-1cd666d824c0.png">

**Comment by HeyCat** [comment]
In staging, messages stacked in order of chronology and were populated on refresh.

**Comment by HeyCat** [comment]
In production, the messages populate in order of chronology, as desired.
