### ISSUE TITLE
Product/Data Entry inventory changes: edit entries

### ISSUE THREAD

**Issue by jkshepperson** [MobilityLabs/pdredesign-server#299]
When viewing the Edit Inventory page, users need to be able to easily edit or make changes to their existing product and data entries.

* When user lands on Edit Inventory page, display all product or data entries with an edit icon next to their row.
* When clicked, display the existing product/data entry modal with all available information pre-populated in the appropriate fields.
* Allow users to make changes to the fields and click 'Done' to save their work.
Reflect the new changes and updates in the system.

**Comment by HeyCat** [comment]
![main_inventory](https://cloud.githubusercontent.com/assets/5464910/15085339/a9e16d28-13a7-11e6-90e4-f027c0b6dc23.png)

**Comment by juliosantos** [comment]
@HeyCat From this image alone, I'm not able to understand the positioning rules for the edit/delete buttons. Are they:

1. hovering on top of every row, always on the right side as the user scrolls either horizontally or vertically?
2. specifically to the right of the "Vendor" column contents?
3. specifically to the right of whichever the last column is?
4. in a new column, to the right of the last one?

I started with 4, but then realized that the buttons will be invisible because the table needs to be scrolled. I'll move them to a new column at the left for now and wait for your feedback.

**Comment by juliosantos** [comment]
We agreed to move the buttons to the left side
