### ISSUE TITLE
Participant view of Analysis Dashboard

### ISSUE THREAD

**Issue by jkshepperson** [MobilityLabs/pdredesign-server#303]
As a participant interacting with the Analysis, I should be able to view the 'Dashboard' of the analysis I am currently reviewing.

**Comment by candyj0311** [comment]
Participants should have the same privileges they do with other dashboards where they are a participant.

**Comment by candyj0311** [comment]
Participants can see the due date and the list of participants (but they cannot manage the participants or make any changes to them). 

They can use the sidebar buttons to go to the connected inventory or to view the analysis report (if applicable). Since the facilitator is the one filling out the analysis, participants should be able to view the state it's currently in, but not make changes to it. They should be able to add and view learning questions and edit questions they've submitted.

**Comment by jkshepperson** [comment]
This a duplicate of #199
