### ISSUE TITLE
Merge outstanding Inventory Edit page functionality to Inventory Report page

### ISSUE THREAD

**Issue by bithavoc** [MobilityLabs/pdredesign-server#308]
Currently the button **Go to Analysis** in the sidebar for the analysis dashboard page is redirecting to analysis assign page regardless of the status of the analysis(`draft | consensus | analysis`).

a good starting point would be:

> investigate what state we arrive at when we've submitted a response to the analysis?  Is there a property on the analysis that we can conveniently access to determine that we've submitted at least one answer?  What about when we've submitted all answers?

Blocked by https://github.com/MobilityLabs/pdredesign-server/issues/267

**Comment by jkshepperson** [comment]
Updating ticket to reflect new changes to smooth out the analysis/inventory navigation and inventory updating processes. For record, here are Johan's comments from Tuesday 5/10:

Currently the button **Go to Analysis** in the sidebar for the analysis dashboard page is redirecting to analysis assign page regardless of the status of the analysis(`draft | consensus | analysis`).

a good starting point would be:

> investigate what state we arrive at when we've submitted a response to the analysis?  Is there a property on the analysis that we can conveniently access to determine that we've submitted at least one answer?  What about when we've submitted all answers?

Blocked by https://github.com/MobilityLabs/pdredesign-server/issues/267

**Comment by jkshepperson** [comment]
For additional reference see ticket #312

**Comment by jkshepperson** [comment]
Updated ticket with new requirements: 

When adding/editing product and data set entries for an inventory, we need to give users additional functionality pieces from the .../inventories/#/edit page so that we can remove the 'edit' page from the workflow and have a concise task route for the users to work through. 

All changes below are requested for the /inventories/#/report page...
[ ] Add the Add/Review Learning Questions button to the report page above the dashboard button, following the same white styling.
[ ] Add the Add Products and Add Data Set green buttons to the Product and Data table sections on the report page.
[ ] Adjust the behavior of the 'Go to Analysis' button to follow this logic:
- If no analysis for the inventory exists, when a user clicks the Go To Analysis button --> display the popup create analysis modal.
- If an analysis exists for the inventory and is **in**complete, when a user clicks the Go To Analysis button --> take user to the analysis page
- If an analysis exists for the inventory and is completed, when a user clicks the Go To Analysis button --> take user to the analysis report page
- If multiple analyses exist for an inventory (regardless of their state), when a user clicks the Go To Analysis button --> take the user to the analysis list page so they can choose which analysis they wish to review
[ ] Migrate the header content for the edit page (located under the inventory header/title) to the report page (place the same content in the same format under the inventory report header/title)
[ ] Adjust navigation from Inventory pages to direct users to the /report page instead of the /edit page. 
- From the Inventory Dashboard page, the Go To Report button should take user to the /report page for the inventory
- From the Inventory List page, ensure all Inventory actions for a given inventory that relate to the /edit page are now pointed to the /report page.

**Comment by jkshepperson** [comment]
Really pretty screenshot to help with clarity:

![mockup](https://cloud.githubusercontent.com/assets/15215098/15294547/b14db912-1b5a-11e6-9f31-f00328f3f91f.png)

**Comment by MakotoTheKnight** [comment]
It seems that the flow is mostly reflective of what we have in place (including the draft state for an analysis), but there is one point I'd like to clarify:

 > If an analysis exists for the inventory and is incomplete, when a user clicks the Go To Analysis button --> take user to the analysis page

Should we take them to the analysis consensus page, or the analysis dashboard?

Also, something I observed while smoke testing the flow as is: the dashboard will link back to the assign page as opposed to taking one to the consensus page.  Should this also be covered with this task?

**Comment by jkshepperson** [comment]
Blocker answers: if an analysis exists for the inventory and is incomplete, when a user clicks the Go To Analysis button --> take user to the analysis dashboard page

**Comment by juliosantos** [comment]
Confirmed with @candyj0311 that a user does not need to be a facilitator to see the analysis button.
