### ISSUE TITLE
Edits to Existing Inventory Data/Product Entries Not Saved

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#349]
I tried editing the existing entries from the DTI Live Test and it wasn't consistently saving what I entered or what I deleted.

**Comment by juliosantos** [comment]
@candyj0311  I think I nailed the root cause of this, but to be honest I'm not 100% sure. My testing on staging shows this working fine, and I'd appreciate you test again (don't be alarmed if you don't find the PEs and DEs created yesterday, I had to get rid of them all).
For now, I'll move on to other tasks for the sake of sprinting.
