### ISSUE TITLE
Investigate invalid assessments

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#97]
We've stumbled across a scenario in which assessments exist in the system that do not have a district.

In terms of the database model, this is confusing since we have an explicit validation to check for the presence of a district.  That is to say, under normal circumstances, we should not be able to persist an assessment without a district.

We wish to determine two things:

 - How this happened, and
 - How we can mitigate the impact.

The likely scenario is that we may be using `update_*` in certain select places (or explicitly disabling validation), so we want to note those occurrences and figure out how the code could enter that state.

There are only a handful of assessments that this has occurred for in production, so we'd like to determine the impact and significance of them not having a district.

**Comment by MakotoTheKnight** [comment]
Broaden scope of task:  investigate usages of `update` in the platform.  Timebox to half a day.

**Comment by juliosantos** [comment]
Note: could be useful to review the application logs. @MakotoTheKnight do we have these stored somewhere or are they ephemeral?

**Comment by juliosantos** [comment]
The Assessment model defines an unconditional `presence` validation on `district_id`, which prevents an Assessment record, *normally*, from being created or updated with a value which .blank? would return true for (nil, empty string, whitespace-only string). This validation has been in place from 1f149276e9476e1a6c7b984a1cd8df07ad91e340 and hasn't been changed in any way since.

The reason for that *normally* is twofold:
- Some ActiveRecord methods bypass this validation.
- This is only relevant within the ActiveRecord context, meaning that any raw SQL instructions or any other way to interact with the database which would bypass ActiveRecord, by definition, bypass the validation. Absent any logs, there's really no way to check that any of these happened, but accidental or deliberate direct database changes will always remain a possibility (and a future risk).

### Hunting for ActiveRecord validation bypasses
Some ActiveRecord methods bypass validation: `decrement!`, `decrement_counter`, `increment!`, `increment_counter`, `toggle!`, `touch`, `update_all`, `update_attribute`, `update_column`, `update_columns`, and `update_counters`.

I used `ack` and `git log -S` to search the codebase and its history for the potential suspects: `update_all`, `update_attribute`, `update_column`, `update_columns`. In order to save time, I deemed the other methods (like `increment!`) to be unlikely to be used to perform a change on the `district_id` field, but can certainly go back and check all of them. Even though some occasionally showed up, I found no instance which could be related to the issue at hand.

It's also possible to bypass model validations by using `validate: false` in a `save` call. Incidentally, I found an instance of this technique, as part of an importer routine, in 2523f34d6f90913465209b336aee3f2370d0fe46. It was removed in 14d62aabe2f40e45d15235cb174c636f4ec47dad, only a few hours later (if the git history is to be trusted). If this code was live in between the 2 commits, this could have been the source of the problem — `lib/assessments/import_data.rb` makes it clear assignments are being created without a district.

### Hunting for raw SQL

It was a long shot, but I tried searching the repository history for `insert into`, `INSERT INTO`, `update assignments` and `UPDATE assignmente` and found nothing relevant.

### Mitigating the impact

I took this to mean "preventing it from happening in the future". In this vein, I have a few suggestions.

- The constraint could be implemented at the database level. To the best of my knowledge, this would all but remove the risk of ActiveRecord validation skipping and all direct database access.
- A log drain could be installed and the log levels detailed enough so that, if the issue is detected again, we can read through them to help us understand the root cause.

If you did mean "minimizing the troubles this caused", I'd need to know more about the model domain to answer. Does the user who creates an assignment always belong to its district? Do the users who participate in one? If any of these are true, we can certainly dig the correct district_id for assignments from its associated models.

**Comment by MakotoTheKnight** [comment]
This looks like it gives us a pretty good jumping-off point to figuring out what's going on.  Specifically, the helper that you had looked at indicated that it was refactored into a helper, which [lives here](https://github.com/MobilityLabs/pdredesign-server/blob/master/app/helpers/import_data_helper.rb).  It seems that we actively use `update_attribute` in those three methods.

**Comment by juliosantos** [comment]
> It seems that we actively use `update_attribute` in those three methods.
We do, but none for `district_id`.

**Comment by juliosantos** [comment]
@MakotoTheKnight, thank for insisting :)
It seems like the current code can indeed cause the problem to happen. In `lib/assessments/import_data.rb`, if `district` is nil, `create_assessment` will fail but `assign_assessment` will cause a database `INSERT`anyway. Below is a simplified behaviour equivalent.
```
2.2.3 :058 > name = "Test Name"
 => "Test Name"
2.2.3 :059 > rubric = Rubric.first
  Rubric Load (1.3ms)  SELECT  "rubrics".* FROM "rubrics"  ORDER BY "rubrics"."id" ASC LIMIT 1
 => #<Rubric id: 1, name: "PD Readiness Rubric", version: #<BigDecimal:7fb84cb88308,'0.1E1',9(18)>, user_id: 2, created_at: "2014-02-21 19:53:17", updated_at: "2014-04-23 13:18:45", enabled: false>
2.2.3 :060 > district = nil
 => nil
 2.2.3 :061 > assessment = Assessment.create(name: name, district: district, rubric_id: rubric_id)
   (0.3ms)  BEGIN
   (0.2ms)  ROLLBACK
 => #<Assessment id: nil, name: "Test Name", due_date: nil, meeting_date: nil, user_id: nil, rubric_id: 0, created_at: nil, updated_at: nil, district_id: nil, message: nil, assigned_at: nil, mandrill_id: nil, mandrill_html: nil, report_takeaway: nil, share_token: nil>
2.2.3 :064 > assessment.update_attribute(:name, "Other Name")
   (0.3ms)  BEGIN
  SQL (1.2ms)  INSERT INTO "assessments" ("name", "rubric_id", "share_token", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "Other Name"], ["rubric_id", 0], ["share_token", "fc8926e4075c9267fc88a1af0ef826ed38513cded0a3383e7b51d94f5548ca53"], ["created_at", "2016-03-22 16:53:12.803391"], ["updated_at", "2016-03-22 16:53:12.803391"]]
   (0.4ms)  COMMIT
 => true
```

**Comment by juliosantos** [comment]
The quick and dirty way to fix this is probably to replace `update_attributes` for `update_attribute`.

**Comment by MakotoTheKnight** [comment]
That sounds like a viable approach, and I agree with it.  We'll capture it in a separate piece of work that we can do when we've got some more time.

**Comment by juliosantos** [comment]
OK. Note that, being a n00b to the project, I have no idea if that code even runs. The problem may come from elsewhere, of course.
Is there anything else you'd like me to do on this?

**Comment by MakotoTheKnight** [comment]
No, I think we're good.  Let's close this task out.
